import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { memoryStore } from '../src/lib/store';
import { assembleReportData } from '../src/lib/reports/reportData';
import { renderReportPdf } from '../src/lib/reports/pdfRenderer';

describe('Server-Side PDF Rendering (§2 & §3)', () => {
  const orgId = 'org_pdf_render_test';

  it('Setup: Initialize Organization with Findings', async () => {
    memoryStore.organizations.set(orgId, {
      _id: orgId,
      id: orgId,
      name: 'Omni Retail Group',
      slug: 'omni-retail',
      plan: 'BUSINESS',
      createdAt: new Date(),
    });

    memoryStore.findings.set('f_pdf_01', {
      _id: 'f_pdf_01',
      organizationId: orgId,
      title: 'Exposed MongoDB Database Without Authentication',
      findingCode: 'PORT-EXPOSED-MONGODB',
      severity: 'CRITICAL',
      confidence: 'CONFIRMED',
      status: 'OPEN',
      riskScore: 92,
      assetFqdn: 'db.omni-retail.com',
      description: 'MongoDB wire protocol accepted unauthenticated query on port 27017.',
      createdAt: new Date(),
    });

    memoryStore.assets.set('a_pdf_01', {
      _id: 'a_pdf_01',
      organizationId: orgId,
      fqdn: 'db.omni-retail.com',
      rootDomain: 'omni-retail.com',
      type: 'SERVICE',
      verificationStatus: 'VERIFIED',
    });
  });

  it('Default Branding Render: Produces valid binary PDF with PLIŌRA branding', async () => {
    const reportData = await assembleReportData(orgId);
    const pdfBuffer = await renderReportPdf(reportData);

    assert.ok(Buffer.isBuffer(pdfBuffer), 'Result must be a binary Node Buffer');
    assert.ok(pdfBuffer.length > 3000, `PDF size must be substantive (got ${pdfBuffer.length} bytes)`);

    // Verify PDF Magic Bytes: %PDF-
    const header = pdfBuffer.subarray(0, 5).toString('ascii');
    assert.strictEqual(header, '%PDF-', 'Buffer must begin with %PDF- header');

    // Verify PDF structure contains expected title metadata
    const pdfText = pdfBuffer.toString('latin1');
    assert.ok(pdfText.includes('Executive Security Report'), 'PDF metadata must contain report title');
    assert.ok(pdfText.includes('PLI'), 'Default PDF must contain PLIORA brand indicator');
  });

  it('White-Label Render (§3): Replaces brand name with custom partner agency', async () => {
    const wlOrgId = 'org_pdf_whitelabel_test';
    memoryStore.organizations.set(wlOrgId, {
      _id: wlOrgId,
      id: wlOrgId,
      name: 'Apex Logistics LLC',
      slug: 'apex-logistics',
      plan: 'PRO',
      reportBranding: {
        whiteLabelEnabled: true,
        customName: 'SecureGrid MSP',
      },
      createdAt: new Date(),
    });

    const reportData = await assembleReportData(wlOrgId);
    assert.strictEqual(reportData.branding.isWhiteLabel, true);
    assert.strictEqual(reportData.branding.brandName, 'SecureGrid MSP');

    const pdfBuffer = await renderReportPdf(reportData);
    assert.ok(Buffer.isBuffer(pdfBuffer));
    assert.ok(pdfBuffer.length > 3000);

    const header = pdfBuffer.subarray(0, 5).toString('ascii');
    assert.strictEqual(header, '%PDF-');

    const pdfText = pdfBuffer.toString('latin1');
    assert.ok(pdfText.includes('SecureGrid MSP'), 'White-label PDF must contain custom brand name');
    assert.ok(!pdfText.includes('Report generated by PLIŌRA'), 'White-label PDF must omit default attribution');
  });
});
