import { isMongoActive } from '@/lib/db';
import { memoryStore } from '@/lib/store';
import { Organization } from '@/models/Organization';
import { AgencyClientLink } from '@/models/AgencyClientLink';
import { Finding } from '@/models/Finding';
import { Asset } from '@/models/Asset';
import { RiskScoreSnapshot } from '@/models/RiskScoreSnapshot';
import { computeOrgRiskScore, OrgRiskScoreResult } from '@/lib/risk/orgScore';
import { generateExecutiveSummary } from '@/lib/ai/analystService';
import { ExecutiveSummaryResult } from '@/lib/ai/types';

export interface ReportFindingItem {
  id: string;
  findingCode: string;
  title: string;
  severity: string;
  confidence: string;
  category: string;
  riskScore: number;
  assetFqdn: string;
  summary: string;
  recommendedAction?: string;
}

export interface ReportTrendPoint {
  date: string;
  score: number;
  grade: string;
}

export interface ReportScopeAsset {
  fqdn: string;
  type: string;
  status: string;
}

export interface ReportBrandingInfo {
  isWhiteLabel: boolean;
  brandName: string;
  customLogo?: string;
  footerText: string;
}

export interface AssembledReportData {
  organization: {
    id: string;
    name: string;
    slug: string;
    plan: string;
  };
  branding: ReportBrandingInfo;
  metadata: {
    generatedAt: string;
    reportDateFormatted: string;
    reportingPeriod: string;
    scopeSummary: string;
  };
  riskScore: {
    score: number;
    securityPosture: number;
    grade: 'A' | 'B' | 'C' | 'D' | 'F';
    factors: OrgRiskScoreResult['factors'];
    findingCounts: OrgRiskScoreResult['findingCounts'];
    explanation: string;
  };
  trend: {
    history: ReportTrendPoint[];
    trendDirection: 'IMPROVING' | 'DEGRADING' | 'STABLE';
    previousScore?: number;
  };
  executiveSummary: {
    summaryText: string;
    overallPosture: string;
    keyRisks: ExecutiveSummaryResult['keyRisks'];
    priorityActions: string[];
    totalConfirmedFindings: number;
    totalHighThreats: number;
  };
  topFindings: ReportFindingItem[];
  scope: {
    totalAssets: number;
    assets: ReportScopeAsset[];
  };
}

/**
 * Pure Data Assembly Engine (§1):
 * Pulls together live organization posture, AI executive summary, score trend history,
 * top 3-5 open findings, and covered assets.
 * 
 * INVARIANT: Zero new scoring or confidence logic. Inherits exactly from live dashboard sources.
 */
export async function assembleReportData(
  organizationId: string,
  options: { actorId?: string; agencyOrgId?: string } = {}
): Promise<AssembledReportData> {
  const orgIdStr = organizationId.toString();

  // 1. Resolve Organization & Branding
  let org: any = null;
  if (isMongoActive()) {
    org = await Organization.findById(organizationId);
  } else {
    org = memoryStore.organizations.get(orgIdStr);
  }

  if (!org) {
    throw new Error(`Organization with ID "${organizationId}" was not found.`);
  }

  // Server-side tier gating (§4 & §5): Only BUSINESS and PRO tiers permit custom white-label branding
  const canAccessWhiteLabel = org.plan === 'BUSINESS' || org.plan === 'PRO';

  let isWhiteLabel = false;
  let brandName = 'PLIŌRA Threat Monitor';
  let customLogo: string | undefined = undefined;
  let footerText = `Report generated by PLIŌRA Threat Monitor • Grounded on confirmed external evidence • Confidential`;

  if (canAccessWhiteLabel) {
    // Check if an active agency link exists (§4)
    let agencyLink: any = null;
    let agencyOrg: any = null;

    if (options.agencyOrgId) {
      const agencyIdStr = options.agencyOrgId.toString();
      if (isMongoActive()) {
        agencyLink = await AgencyClientLink.findOne({
          agencyOrgId: options.agencyOrgId,
          clientOrgId: org._id,
          status: 'ACTIVE',
        });
        if (agencyLink) {
          agencyOrg = await Organization.findById(options.agencyOrgId);
        }
      } else {
        const links = Array.from(memoryStore.agencyClientLinks.values());
        agencyLink = links.find(
          (l: any) =>
            (l.agencyOrgId?.toString() === agencyIdStr || l.agencyOrgId === agencyIdStr) &&
            (l.clientOrgId?.toString() === orgIdStr || l.clientOrgId === orgIdStr) &&
            l.status === 'ACTIVE'
        );
        if (agencyLink) {
          agencyOrg = memoryStore.organizations.get(agencyIdStr);
        }
      }
    } else {
      // Check for any active agency link with delegateBranding
      if (isMongoActive()) {
        agencyLink = await AgencyClientLink.findOne({
          clientOrgId: org._id,
          status: 'ACTIVE',
          delegateBranding: true,
        });
        if (agencyLink) {
          agencyOrg = await Organization.findById(agencyLink.agencyOrgId);
        }
      } else {
        const links = Array.from(memoryStore.agencyClientLinks.values());
        agencyLink = links.find(
          (l: any) =>
            (l.clientOrgId?.toString() === orgIdStr || l.clientOrgId === orgIdStr) &&
            l.status === 'ACTIVE' &&
            l.delegateBranding === true
        );
        if (agencyLink) {
          const aIdStr = (agencyLink.agencyOrgId?._id || agencyLink.agencyOrgId).toString();
          agencyOrg = memoryStore.organizations.get(aIdStr);
        }
      }
    }

    const clientReportBranding = org.reportBranding || {};
    const agencyReportBranding = agencyOrg?.reportBranding || {};

    // Branding Precedence Hierarchy (§4):
    // Rule A: Explicit delegation (delegateBranding: true) -> Agency branding
    if (agencyLink?.delegateBranding && agencyReportBranding.whiteLabelEnabled) {
      isWhiteLabel = true;
      brandName = agencyReportBranding.customName || agencyOrg.name;
      customLogo = agencyReportBranding.customLogo;
      footerText = `Report prepared for ${org.name} by ${brandName} • Strictly confidential`;
    }
    // Rule B: Client explicit custom branding (if client configured their own)
    else if (clientReportBranding.whiteLabelEnabled) {
      isWhiteLabel = true;
      brandName = clientReportBranding.customName || org.name;
      customLogo = clientReportBranding.customLogo;
      footerText = `Report prepared for ${org.name} • Strictly confidential`;
    }
    // Rule C: Agency default branding fallback (if active link exists and agency has branding)
    else if (agencyLink && agencyReportBranding.whiteLabelEnabled) {
      isWhiteLabel = true;
      brandName = agencyReportBranding.customName || agencyOrg.name;
      customLogo = agencyReportBranding.customLogo;
      footerText = `Report prepared for ${org.name} by ${brandName} • Strictly confidential`;
    }
  }

  // 2. Resolve Live Risk Score, Grade & Posture (Option 3)
  const riskScoreData: OrgRiskScoreResult = await computeOrgRiskScore(orgIdStr);

  // 3. Resolve Risk Score Trend History
  let rawSnapshots: any[] = [];
  if (isMongoActive()) {
    rawSnapshots = await RiskScoreSnapshot.find({ organizationId })
      .sort({ computedAt: -1 })
      .limit(30)
      .lean();
  } else {
    rawSnapshots = (memoryStore.riskScoreSnapshots || [])
      .filter((s: any) => s.organizationId?.toString() === orgIdStr)
      .sort((a: any, b: any) => new Date(b.computedAt).getTime() - new Date(a.computedAt).getTime())
      .slice(0, 30);
  }

  // Reverse snapshots to chronological order for trend
  const chronological = [...rawSnapshots].reverse();
  const trendHistory: ReportTrendPoint[] = chronological.map((s) => ({
    date: new Date(s.computedAt || s.createdAt).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
    }),
    score: s.score,
    grade: s.grade,
  }));

  let trendDirection: 'IMPROVING' | 'DEGRADING' | 'STABLE' = 'STABLE';
  let previousScore: number | undefined = undefined;

  if (chronological.length >= 2) {
    previousScore = chronological[chronological.length - 2].score;
    if (previousScore !== undefined) {
      if (riskScoreData.score < previousScore) {
        trendDirection = 'IMPROVING'; // Lower risk score is safer
      } else if (riskScoreData.score > previousScore) {
        trendDirection = 'DEGRADING'; // Higher risk score is more exposed
      }
    }
  }

  // 4. Resolve AI Executive Summary (Option 7 §8: CONFIRMED/HIGH only)
  const execSummaryResult: ExecutiveSummaryResult = await generateExecutiveSummary(orgIdStr, {
    actorId: options.actorId,
  });

  // 5. Gather Top 5 Open Findings (Matching Dashboard Home query)
  let rawFindings: any[] = [];
  if (isMongoActive()) {
    rawFindings = await Finding.find({
      organizationId,
      status: 'OPEN',
    })
      .sort({ riskScore: -1, createdAt: -1 })
      .limit(5)
      .lean();
  } else {
    rawFindings = Array.from(memoryStore.findings.values())
      .filter((f: any) => f.organizationId?.toString() === orgIdStr && f.status === 'OPEN')
      .sort((a: any, b: any) => (b.riskScore || 0) - (a.riskScore || 0))
      .slice(0, 5);
  }

  const topFindings: ReportFindingItem[] = rawFindings.map((f: any) => ({
    id: (f._id || f.id).toString(),
    findingCode: f.findingCode || 'SEC-FINDING',
    title: f.title,
    severity: f.severity,
    confidence: f.confidence,
    category: f.category || 'GENERAL',
    riskScore: f.riskScore || 0,
    assetFqdn: f.assetFqdn || f.target || org.name,
    summary: f.description || f.summary || f.title,
    recommendedAction: f.remediationGuidance?.summary || f.recommendedAction,
  }));

  // 6. Gather Assessment Scope Assets
  let rawAssets: any[] = [];
  if (isMongoActive()) {
    rawAssets = await Asset.find({ organizationId })
      .select('fqdn type verificationStatus')
      .lean();
  } else {
    rawAssets = Array.from(memoryStore.assets.values()).filter(
      (a: any) => a.organizationId?.toString() === orgIdStr
    );
  }

  const scopeAssets: ReportScopeAsset[] = rawAssets.map((a: any) => ({
    fqdn: a.fqdn || a.rootDomain || 'unknown',
    type: a.type || 'ROOT_DOMAIN',
    status: a.verificationStatus || 'VERIFIED',
  }));

  // 7. Generation Timestamps & Formatted Period
  const now = new Date();
  const reportDateFormatted = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const reportingPeriod = `As of ${reportDateFormatted}`;
  const scopeSummary = `${scopeAssets.length} monitored asset${scopeAssets.length === 1 ? '' : 's'} across active attack surface`;

  return {
    organization: {
      id: orgIdStr,
      name: org.name,
      slug: org.slug || org.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      plan: org.plan || 'FREE',
    },
    branding: {
      isWhiteLabel,
      brandName,
      customLogo,
      footerText,
    },
    metadata: {
      generatedAt: now.toISOString(),
      reportDateFormatted,
      reportingPeriod,
      scopeSummary,
    },
    riskScore: {
      score: riskScoreData.score,
      securityPosture: riskScoreData.securityPosture,
      grade: riskScoreData.grade,
      factors: riskScoreData.factors,
      findingCounts: riskScoreData.findingCounts,
      explanation: riskScoreData.explanation,
    },
    trend: {
      history: trendHistory,
      trendDirection,
      previousScore,
    },
    executiveSummary: {
      summaryText: execSummaryResult.executiveSummary,
      overallPosture: execSummaryResult.overallPosture,
      keyRisks: execSummaryResult.keyRisks,
      priorityActions: execSummaryResult.priorityActions.map((act: any) =>
        typeof act === 'string' ? act : (act as any).title || JSON.stringify(act)
      ),
      totalConfirmedFindings: execSummaryResult.totalConfirmedFindings,
      totalHighThreats: execSummaryResult.totalHighThreats,
    },
    topFindings,
    scope: {
      totalAssets: scopeAssets.length,
      assets: scopeAssets,
    },
  };
}
